name: Publish to PyPI

on:
  release:
    types: [published]

  workflow_dispatch:

env:
  PIP_DISABLE_PIP_VERSION_CHECK: "1"

jobs:
  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for trusted publishing

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build package
        run: python -m build

      - name: Check package
        run: twine check dist/*

      # Preferred: Trusted Publishing via OIDC (no token required)
      - name: Publish to PyPI (Trusted Publishing)
        if: ${{ secrets.PYPI_API_TOKEN == '' }}
        uses: pypa/gh-action-pypi-publish@release/v1

      # Fallback: API token if provided as a secret
      - name: Publish to PyPI (API token)
        if: ${{ secrets.PYPI_API_TOKEN != '' }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
